name = "jarvis-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# [vars]
# MY_VARIABLE = "production_value"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[[d1_databases]]
binding = "DB"
database_name = "jarvis-d1"
database_id = "b9fa7b62-3a1d-45f1-906a-c1d20e47b3c7"
